### ISSUE TITLE
Makefile error while installing using luarocks

### ISSUE THREAD

**Issue by ALENTL** [mah0x211/lauxhlib#10]
![image](https://user-images.githubusercontent.com/82425585/178486338-adc64891-cec7-4705-b4d4-5d81de31aa3e.png)

**Comment by ALENTL** [comment]
![image](https://user-images.githubusercontent.com/82425585/178987114-d77cbf75-b6f4-4339-9848-f8df128f3a8d.png)

**Comment by ALENTL** [comment]
@mah0x211 Please fix this issue soon. On windows

**Comment by mah0x211** [comment]
It seems that lauxlib.h is not installed.
I do not know the programming environment on windows, so if you have a problem on windows and want to fix it and make it work, please send me a PR.
